// Autenticacion
export const LOGIN_EXITO = "LOGIN_EXITO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const CERRAR_SESION = "CERRAR_SESION";

// Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

// Empleados
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";
export const REGISTRAR_USUARIO_ERROR = "REGISTRAR_USUARIO_ERROR";
export const ELIMINAR_USUARIO_EXITO = "ELIMINAR_USUARIO_EXITO";
export const ELIMINAR_USUARIO_ERROR = "ELIMINAR_USUARIO_ERROR";
export const OBTENER_USUARIO_EXITO = "OBTENER_USUARIO_EXITO";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";

// Global
export const LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";