// Autenticacion
export const LOGIN_EXITO = "LOGIN_EXITO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const CERRAR_SESION = "CERRAR_SESION";

// Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

// Empleados
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";
export const ELIMINAR_USUARIO_EXITO = "ELIMINAR_USUARIO_EXITO";
export const OBTENER_USUARIO_EXITO = "OBTENER_USUARIO_EXITO";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";

// Productos
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";
export const OBTENER_PRODUCTO_EXITO = "OBTENER_PRODUCTO_EXITO";
export const OBTENER_PRODUCTO_ERROR = "OBTENER_PRODUCTO_ERROR";
export const CREAR_PRODUCTO_EXITO = "CREAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";
export const ACTUALIZAR_PRODUCTO_EXITO = "ACTUALIZAR_PRODUCTO_EXITO";
// Paginacion productos
export const PAGINA_SIGUIENTE = "PAGINA_SIGUIENTE";
export const PAGINA_ANTERIOR = "PAGINA_SIGUIENTE";

// Gastos
export const ASIGNAR_PRODUCTOS_GASTO = "ASIGNAR_PRODUCTOS_GASTO";
export const RESUMEN_PRODUCTO = "RESUMEN_PRODUCTO";
export const LIMPIAR_PRODUCTOS_GASTO = "LIMPIAR_PRODUCTOS_GASTO";
export const OBTENER_GASTOS_EXITO = "OBTENER_GASTOS_EXITO";
export const ELIMINAR_GASTO_EXITO = "ELIMINAR_GASTO_EXITO";
export const OBTENER_GASTO_ERROR = "OBTENER_GASTO_ERROR";
export const NUEVO_GASTO_EXITO = "NUEVO_GASTO_EXITO";
export const NUEVO_GASTO_TOTAL = "NUEVO_GASTO_TOTAL";
export const OBTENER_GASTO_EXITO = "OBTENER_GASTO_EXITO";
export const EDITAR_GASTO_EXITO = "EDITAR_GASTO_EXITO";

// Global
export const LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";
